### ISSUE TITLE
IllegalAccessError with hbase-driver and guava

### ISSUE THREAD

**Issue by jfelipeoliveira90** [eclipse/jnosql-diana#91]
The hbase-client uses dependencies that conflict with the newer versions of guava, as detailed: http://stackoverflow.com/questions/36427291/illegalaccesserror-to-guavas-stopwatch-from-org-apache-hadoop-mapreduce-lib-inp

To resolve this problem, you must add the latest hadoop-mapreduce-client-core dependency in the project pom.

**Comment by otaviojava** [comment]
Hey @jfelipeoliveira90 
I removed the guava dependency to use Standard JSON.
Could you check if that ok now, please?
https://github.com/eclipse/jnosql-diana-driver/issues/29

If the error persists, please, let us know and reopen this issue.

Thanks
