### ISSUE TITLE
Replace Settings with a more generic configuration element

### ISSUE THREAD

**Issue by keilw** [eclipse/jnosql-diana#99]
The `Settings` interface does pretty much the same thing as `Config` or Configuration from MicroProfile Config API or the recently approved JSR 382. 
Could we work on deprecating that in favor of using JSR 382 or (if necessary until 382 reaches a phase like EDR) at least MicroProfile Config 1.1?

**Comment by otaviojava** [comment]
Sure, that's sound the better idea.

**Comment by keilw** [comment]
Happy to help with that. Like @atsticks I recently joined the JSR 382 EG. I'll meet him tomorrow where I talk about JSR 375 and he does about Config/MP. so we can discuss integration into other projects.

**Comment by otaviojava** [comment]
https://github.com/eclipse/ConfigJSR/issues/52#issuecomment-363501802

**Comment by otaviojava** [comment]
As you can see, the initial JSR configuration won't cover the Java SE API, so I'll close this issue for while.
